[project]
name = "gestion de productos"
version = "0.1.0"
description = "Monolithic Async Application with FastAPI + Flet"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Flet developer", email = "you@example.com" }
]
dependencies = [
    "flet>=0.80.2",
    "fastapi",
    "uvicorn[standard]",
    "sqlmodel",
    "sqlalchemy[asyncio]",
    "aiosqlite",
    "httpx",
    "python-dotenv",
    "asyncpg",
]

[dependency-groups]
dev = [
    "flet[all]>=0.80.2",
]

[project.optional-dependencies]
dev = ["pytest"]

[tool.flet]
org = "com.example"
product = "gestion de productos"
company = "My Company"
copyright = "Copyright (C) 2026 by My Company"

[tool.flet.app]
path = "src"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
